action_list:

  number_of_targets: 3

  action_0:
    action_type: pose
    translation: [0.4, 0.3, 0.1]
    orientation: [0.0, 0.0, 1.5]
    duration: 5.0

  action_1:
    action_type: pose
    translation: [0.4, -0.3, 0.1]
    orientation: [0.0, 0.0, 1.5]
    duration: 5.0

  action_2:
    action_type: pose
    translation: [ 0.4, -0.3, 0.45]
    orientation: [ 0.0, 0.0, 1.5]
    duration: 4.0

