#Joint Space
# joint stiffness and damping parameters

joint_stiffness: 60.0
joint_stiffness_2: 60
joint_damping: 10.0
joint_damping_2: 10.0

# Task Space
# End-effector stiffness and damping parameters
end_effector_stiffness: 52.25
end_effector_stiffness_2: 70.25
end_effector_damping: 5.0
end_effector_damping_2: 10.0

