#Joint Space
# joint stiffness and damping parameters

joint_stiffness: 60.0
joint_stiffness_2: 100.0
joint_damping: 10.0
joint_damping_2: 15.0

# Task Space
# End-effector stiffness and damping parameters
end_effector_stiffness: 55.0
end_effector_stiffness_2: 80.0
end_effector_damping: 20.0
end_effector_damping_2: 8.0


